# Generated by Django 5.1.1 on 2024-09-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
